blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Feature Requests & Questions
    url: https://github.com/replaysMike/Binner/discussions
    about: Please ask and answer questions here, but don't report bugs here! That's what bug reports/issues are for!
  - name: ðŸ‘¾ Community Chat
    url: https://discord.gg/74GEJY5g7G
    about: Join the Discord to discuss bugs, feature suggestions, and getting help!